export const COLLEGES = [
    "SRM TRPEC",
    "SRMIST FET",
    "SRM COLLEGE OF ALLIED HEALTH AND SCIENCE",
    "SRM OCCUPATIONAL THERAPY IST",
    "SRM PHYSIOTHERAPY IST",
    "SRM AHS MGR",
    "SRMIST FSH",
    "SRM TRICHY ARTS AND SCIENCE",
    "SRM MEDICAL COLLEGE",
    "SRM FACULTY OF MANAGEMENT",
    "SRM INSTITUE OF HOTEL MANAGEMENT",
    "SRM COLLEGE OF NURSING"
];

export const YEARS = [ "1st", "2nd", "3rd", "4th", "5th" ];
