import { FileText } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#13072E] text-white px-6 py-32 relative overflow-hidden">
      {/* Background Glows */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-[#22D3EE]/5 blur-[150px] rounded-full pointer-events-none" />

      <div className="max-w-4xl mx-auto bg-white/5 border border-white/10 rounded-3xl p-8 md:p-12 backdrop-blur-xl shadow-2xl relative z-10">
        
        <div className="flex items-center gap-4 mb-8 border-b border-white/10 pb-8">
            <div className="p-3 rounded-xl bg-[#22D3EE]/10 border border-[#22D3EE]/30">
                <FileText className="w-8 h-8 text-[#22D3EE]" />
            </div>
            <h1 className="text-4xl md:text-5xl font-black text-white" style={{ fontFamily: "'Playfair Display', serif" }}>
                Terms of <span className="text-[#22D3EE] italic">Service</span>
            </h1>
        </div>

        <p className="text-white/70 leading-relaxed mb-8 text-lg">
          By accessing the RasRang portal and securing event passes, you agree to abide by the following terms established by the SRM Trichy organizing committee.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4 text-white">1. Ticket Validity & Scanning</h2>
        <ul className="list-disc ml-6 text-white/70 leading-relaxed space-y-2 mb-6">
          <li>Digital Entry Passes (QR Codes) generated by this platform are strictly <strong>non-transferable</strong>.</li>
          <li>Attempting to modify, duplicate, screenshot, or share your dynamic QR code will result in the immediate invalidation of your pass.</li>
          <li>Each pass is valid for a single scan at the designated venue checkpoint.</li>
        </ul>

        <h2 className="text-2xl font-bold mt-8 mb-4 text-white">2. Right of Admission</h2>
        <p className="text-white/70 leading-relaxed mb-6">
          Possession of a digital ticket does not guarantee absolute entry. The RasRang '26 organizing committee and SRM Trichy campus security reserve the right of admission. Entry may be denied if an attendee violates the campus code of conduct, appears intoxicated, or poses a safety risk.
        </p>

        <h2 className="text-2xl font-bold mt-8 mb-4 text-white">3. Event Modifications</h2>
        <p className="text-white/70 leading-relaxed mb-6">
          All event timings, headliner appearances, and venue locations are subject to change. The organizing committee is not liable for any last-minute adjustments necessitated by technical, weather, or logistical constraints.
        </p>

      </div>
    </div>
  );
}
